### ISSUE TITLE
Error returned when file name exists

### ISSUE THREAD

**Issue by Nateowami** [koopero/node-unique-file-name#2]
I'm having an issue that an error is returned to the callback if a file with the given name already exists.

My format string is is `%f%i`. What I'm trying to do is preserve the original file name as much as possible, but when a second `file.txt` is uploaded, name it something like `file2.txt`. This seems like a pretty standard use-case.

What happens is, [main.js:52](https://github.com/koopero/node-unique-file-name/blob/c1071c681470b6e33c56712592e9f0deb2f467a4/src/main.js#L52) calls `fs.exists`. Upon finding that the file exists, [main.js:60](https://github.com/koopero/node-unique-file-name/blob/c1071c681470b6e33c56712592e9f0deb2f467a4/src/main.js#L60) calls back with the "error", which is actually just `true`. Error handlers then log `true` and nothing more (that took awhile to debug!).

I think there are two issues here:
- An error should be constructed, so there will be a message and a stack trace.
- If I'm understanding correctly, it seems it should increment the counter (`%i`) and try again. Am I wrong?

---

Looking a bit deeper I think I see the issue. [fs.exists](https://nodejs.org/api/fs.html#fs_fs_exists_path_callback) calls back with a _single_ argument (very unconventional for Node.js, and apparently [the main reason for its deprecation.](https://github.com/nodejs/node/issues/1592#issuecomment-100688675)), telling whether the file exists. The `onExists` function ([main.js:58](https://github.com/koopero/node-unique-file-name/blob/c1071c681470b6e33c56712592e9f0deb2f467a4/src/main.js#L58)) expects the first argument to be `err`. Hence, when the file exists, it calls back with `true` rather than trying another iteration.

This might be a good time to switch to [`fs.open`](https://nodejs.org/api/fs.html#fs_fs_open_path_flags_mode_callback), probably using the `wx+` mode (`fs.exists` being deprecated). In that case it would be necessary to catch errors from `fs.open` that will be thrown if the file exits already.

I can't commit to anything, but I might be able to submit a pull request.

**Comment by koopero** [comment]
I have published a new version ( 0.1.5 ), which fixes this problem.
Thanks for the bug report.

**Comment by Nateowami** [comment]
Thanks! I'll give it a try. And thanks for updating the documentation clarifying the difference between `%f` and `%b`.
